server:
  port: ${PORT:8083}
  servlet:
    context-path: /consumer-service
spring:  
  application:
    name: consumer-service
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/