server:
  port: ${PORT:8084}
  servlet:
    context-path: /course-service
spring:  
  application:
    name: course-service
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/