server:
  port: ${PORT:8085}
  servlet:
    context-path: /article-service
spring:  
  application:
    name: article-service
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/