server:
  port: ${PORT:8081}
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:  
  application:
    name: authentication-service
zuul:
  routes:
    consumer-service:
      path: /consumer-service/**
      serviceId: consumer-service
    product-service:
      path: /product-service/**
      serviceId: product-service