server:
  port: ${PORT:8082}
  servlet:
    context-path: /product-service
spring:  
  application:
    name: product-service
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/